export const eventsData = [
    {
        image: "/assets/event01.png",
        title: "Legends Rise on the Field",
        date: "Thu, Dec 5",
        time: "12.30AM - 12.30PM",
        location: "Bashundhara Sports Complex",
        attendance: "6/8",
        spotsLeft: "2",
        price: "320",
    },
    {
        image: "/assets/event02.png",
        title: "Chasing Glory: Football Showdown",
        date: "Thu, Dec 5",
        time: "12.30AM - 12.30PM",
        location: "Bashundhara Sports Complex",
        attendance: "6/8",
        spotsLeft: "2",
        price: "320",
    },
    {
        image: "/assets/event01.png",
        title: "United We Play, United Win",
        date: "Thu, Dec 5",
        time: "12.30AM - 12.30PM",
        location: "Bashundhara Sports Complex",
        attendance: "6/8",
        spotsLeft: "2",
        price: "320",
    },
    {
        image: "/assets/event02.png",
        title: "Chasing Glory: Football Showdown",
        date: "Thu, Dec 5",
        time: "12.30AM - 12.30PM",
        location: "Bashundhara Sports Complex",
        attendance: "6/8",
        spotsLeft: "2",
        price: "320",
    },
];