import Navbar from "@/components/layouts/Navbar";
import "./globals.css"

export const metadata = {
  title: "Frontend Assignment | Abdullah",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=National+Park:wght@200..800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="text-gray-800 bg-background">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
